### ISSUE TITLE
Milestone 2: Document summarization

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/ask-xDD#74]
Dec 2023 - March 2024

Subtask 2.1: 

- [x] #89

Subtask 2.2: Linking extractions

- [ ] Implement a model identified in Subtask 2.1 to link together extractions within document (e.g., equation to table value) to generate wholistic extracted responses

Subtask 2.3: Document-level summaries of key concepts/ideas

- [ ] Given a particular PDF, generate document level summaries with appropriate links to extractions and other papers.

Subtask 2.4: (If time allows) 

- [ ] Implement additional models identified during subtask 2.1

**Comment by JasonLo** [comment]
Updated [SoW](https://docs.google.com/document/d/1tKAfmXl2cKxwIz70r_NnVChsQSkFu_wJObGnp2O-Fpk/edit) after Nov 30, 2023 meeting.
